/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/6_Pounder_Brass_Cannon.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/6_Pounder_Brass_Cannon.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.061, 2.594, -0.882]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Dark_Steel} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Dark_Steel.001']} />
        <mesh geometry={nodes.Cube006_3.geometry} material={materials.Rope} />
        <mesh geometry={nodes.Cube006_4.geometry} material={materials.Gun_Barrel} />
      </group>
    </group>
  )
}

useGLTF.preload('/6_Pounder_Brass_Cannon.glb')
